### ISSUE TITLE
Optics

### ISSUE THREAD

**Issue by willrogers** [willrogers/at#11]
> Another point is: what’s next ? You brought the engine, but AT is thousands of lines of Matlab code. I was thinking of “atlinopt” and a few convenience routines to extract/modify lattice parameters (atgetcells, atgetfieldvalues, atsetfieldvalues…). Do you already have plans ?

I was going to base the requirements on what I need for a python middle layer type application: twiss parameters, tunes etc.

There is a lot of stuff in AT, but there's no need to make a complete clone, at least to start with, and translating Matlab to Python is relatively straightforward.  The code should be more compact in Python as well.

**Comment by bnash** [comment]
Here is a simple function to compute the 6x6 one turn map matrix.  From this we can compute generalized Twiss parameters, invariants, etc.  May still be a good idea to have uncoupled limits to get simple Twiss params.

import at
import elements
import numpy
import load_mat

def pyATm66(ring):
    eps=1e-10
    epsmat=eps*numpy.identity(6)
    mm=at.atpass(ring, epsmat, 1)/eps
    return numpy.transpose(mm)

**Comment by willrogers** [comment]
Three backticks before the code and three backticks afterwards.

**Comment by willrogers** [comment]
(Backtick is top-left on the UK keyboard).

**Comment by bnash** [comment]
Thanks, next step is to make a version of the amat function
https://github.com/willrogers/at/blob/pyat/atmat/atphysics/amat.m
in python.

From there, we can also make generalized lattice functions with Forests 'betaoids' and 'etaoids'
http://journals.aps.org/pre/abstract/10.1103/PhysRevE.58.2481

https://github.com/willrogers/at/blob/pyat/atmat/pubtools/local_lattice_params/find_betaoids.m

We also need to make utilities for computing things at different places around the ring.  Many of the functions in Matlab AT accept a set of indices that compute the quantities at those positions in the lattice.

**Comment by bnash** [comment]
amat can also be used to compute eigenemittance following computing second moment matrix (Sigma) from ohmi-envelope
https://github.com/willrogers/at/blob/pyat/atmat/atphysics/ohmienvelope.m
Though, I think the eigenvalues of J*Sigma also give you the emittances.

**Comment by willrogers** [comment]
This issue was moved to atcollab/at2devel#5
