### ISSUE TITLE
Numpy arrays are transposed with respect to Matlab ones

### ISSUE THREAD

**Issue by willrogers** [willrogers/at#27]
AT requires input of shape `(6, x)`.
pyAT requires input of shape `(x, 6)`.

The difference is confusing.  I cannot remember if there is a technical reason why this is, or if it could be corrected to be the same.

Perhaps @lfarv can remember.

**Comment by lfarv** [comment]
The integrators, ruling on a set on several particles rely on the fact that the 6 coordinates of one particle are consecutive  in memory, and the 2nd particle follows the 1st one. With the default ordering of Matlab and Python, this corresponds to 
6xN in Matlab and Nx6 in numpy. It should also accept 6xN numpy arrays with Fortran-ordering, but it is probably safer to use the default ordering.

**Comment by willrogers** [comment]
Thanks for explaining this.  We have a couple of options here.

* Switch to using Fortran-aligned arrays.  I might prefer this, since the comparability of the output for AT and pyAT improves.  The disadvantage is that the user needs to create Fortran-aligned arrays and they won't be expecting to.
* Keep with C-aligned arrays.  The opposite of the above.
* Don't use `atpass` directly - use a Python function that checks the arguments and converts if necessary.

Usability and absolute speed may conflict here, but I am finding the differences in algorithms between AT and pyAT (due to the transpose) a little tedious.

**Comment by willrogers** [comment]
This issue was moved to atcollab/at2devel#7
