### ISSUE TITLE
atpass.py missing in repo

### ISSUE THREAD

**Issue by smartsammler** [willrogers/at#45]
The tests fail when trying to import atpass.
Since there is no file named `at/atpass.py` I think it is just missing in the github repo.

```
ImportError while importing test module '[…]/pyat/test/test_atpass.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/test_atpass.py:3: in <module>
    from at import elements, atpass
at/__init__.py:2: in <module>
    from at.atpass import atpass
E   ImportError: No module named 'at.atpass'
```

**Comment by smartsammler** [comment]
Probably missed one step.
Works now, since the atpass is part of the C extension.

Sorry.

**Comment by willrogers** [comment]
Hi, good to have you testing (I've been on leave for a couple of weeks).  If you have any comments or suggestions for usability, capability or documentation, please let me know.

It gets interesting if you can import your lattice and get the same results to those from Matlab.
