### ISSUE TITLE
problem with "load_mat.load"

### ISSUE THREAD

**Issue by lfarv** [willrogers/at#47]
`load_mat.load` alters the `Class` field  of elements before using them, using the `title()` method. But class names are case sensitive and sometimes use capital letters in the middle, for instance `RingParam` or `ThinMultipole` (CamelCase standard). So `load_mat.load` fails when loading such elements. Class names are automatically set in element creation routines and I think they should be kept as they are.

**Comment by willrogers** [comment]
This issue was moved to atcollab/at2devel#8
