### ISSUE TITLE
Improve speed

### ISSUE THREAD

**Issue by willrogers** [willrogers/at#7]
The most likely way to speed up execution is to follow the Matlab method - that is, it fetches attributes from the elements on the first turn of the ring, then caches them for use on subsequent turns.

This saves retrieving data from Python / Matlab for each element for each turn.

**Comment by willrogers** [comment]
It may be possible to profile execution using [yep](https://pypi.python.org/pypi/yep)

**Comment by carmignani** [comment]
Hello Will,
we discussed at lunch about how to improve the speed and we thought that we could copy all the needed fields of the matlab/python structure in a C structure inside the passmethod at the first turn. 
I will work on this and I will check the speed on matlab in the next days. It should improve a lot the speed for the python version and it should improve a bit also in matlab.

**Comment by willrogers** [comment]
Sounds great, thanks for contributing.

The only thing I think of is that the same pass method can be used by different elements, so you will somehow need to store all the fields for all the elements and select the correct ones for the element when calling the pass method.

**Comment by bnash** [comment]
I think this is right, Will.  But what makes it easier is that each pass method knows what structure it needs.  So, when an element is called for the first time in atpass.c (at.c in python), when it calls the pass method, the pass method itself will construct this structure.  So the pass methods need to be modified (Passfunction or Trackfunction in Matlab and atpyPass for Python).  Hopefully the change to these entry points is very similar for both Matlab and Python (or could even be combined via #ifdefs)
Something like this is what I understood from our lunch conversation...

**Comment by willrogers** [comment]
See #9.

**Comment by willrogers** [comment]
Work by @carmignani and @lfarv has given about a 5x speed-up, making the Python version equivalent to the Matlab version.
